apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actableai.fullname" . }}-config
  labels:
    {{- include "actableai.labels" . | nindent 4 }}
type: Opaque
stringData:
  superset_config.py: |
{{- include "actableai-config" . | nindent 4 }}
  superset_init.sh: |
{{- tpl .Values.init.initscript . | nindent 4 }}

{{- if .Values.extraSecrets }}
{{- range $path, $config := .Values.extraSecrets }}
  {{ $path }}: |
{{- tpl $config $ | nindent 4 -}}
{{- end -}}
{{- end -}}
