apiVersion: v1
kind: Secret
metadata:
  name: {{ include "actableai.fullname" . }}-env
  labels:
    {{- include "actableai.labels" . | nindent 4 }}
type: Opaque
stringData:
    REDIS_HOST: {{ tpl .Values.actableaiNode.connections.redis_host . | quote }}
    REDIS_PORT: {{ .Values.actableaiNode.connections.redis_port | quote }}
    SYSTEM_DB_HOST: {{ tpl .Values.actableaiNode.connections.system_db_host . | quote }}
    SYSTEM_DB_NAME: {{ tpl .Values.actableaiNode.connections.system_db_name . | quote }}
    SYSTEM_DB_USER: {{ tpl .Values.actableaiNode.connections.system_db_user . | quote }}
    SYSTEM_DB_PASS: {{ tpl .Values.actableaiNode.connections.system_db_pass . | quote }}
    SYSTEM_DB_PORT: {{ tpl .Values.actableaiNode.connections.system_db_port . | quote }}
    EXAMPLE_DB_HOST: {{ tpl .Values.actableaiNode.connections.example_db_host . | quote }}
    EXAMPLE_DB_NAME: {{ tpl .Values.actableaiNode.connections.example_db_name . | quote }}
    EXAMPLE_DB_USER: {{ tpl .Values.actableaiNode.connections.example_db_user . | quote }}
    EXAMPLE_DB_PASS: {{ tpl .Values.actableaiNode.connections.example_db_pass . | quote }}
    EXAMPLE_DB_PORT: {{ tpl .Values.actableaiNode.connections.example_db_port . | quote }}
    CELERY_DB_HOST: {{ tpl .Values.actableaiNode.connections.example_db_host . | quote }}
    CELERY_DB_NAME: {{ tpl .Values.actableaiNode.connections.example_db_name . | quote }}
    CELERY_DB_USER: {{ tpl .Values.actableaiNode.connections.example_db_user . | quote }}
    CELERY_DB_PASS: {{ tpl .Values.actableaiNode.connections.example_db_pass . | quote }}
    CELERY_DB_PORT: {{ tpl .Values.actableaiNode.connections.example_db_port . | quote }}
    {{- if .Values.extraSecretEnv }}
    {{- range $key, $value := .Values.extraSecretEnv }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}